# Generated by Django 2.2.1 on 2019-10-25 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('likes', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quora.Question')),
            ],
        ),
    ]
