# Generated by Django 2.2.1 on 2019-10-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='likes',
        ),
        migrations.AddField(
            model_name='question',
            name='Dp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='arrays',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='graphs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='greedy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='strings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='trees',
            field=models.BooleanField(default=False),
        ),
    ]
